# Generated by Django 4.2.11 on 2024-06-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordermodel', verbose_name='سفارش والد')),
            ],
            options={
                'verbose_name': 'موارد سفارش',
                'verbose_name_plural': 'موارد سفارشات',
            },
        ),
    ]
