# Generated by Django 4.2.11 on 2024-06-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_count_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='done',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حال تحویل'), (2, 'تحویل داده شده'), (3, 'پرداخت شده')], default=1, verbose_name='تحویل داده شده'),
        ),
    ]
