# Generated by Django 4.2.11 on 2024-06-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ordermodel_done_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='desc',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='توضیحات'),
        ),
    ]
