# Generated by Django 4.2.11 on 2024-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordermodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
