# Generated by Django 5.0.3 on 2024-03-07 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categorymodel', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
